version: '3.4'

services:
  cookpiapp:
    image: cookpiapp
    build:
      context: .
      dockerfile: ./Dockerfile
  redis:
    image: "redis:latest"
    container_name: cookpi
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    #environment:
    #  - REDIS_HOST=cookpi.redis.cache.windows.net
    #  - REDIS_PORT=6380
    #  - REDIS_SSL=True
    #  - REDIS_PASSWORD=vDzc42AZlVCiHn58bddYfUc5RLmvUkCKmAzCaJdPs8Q=
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379