services:
  # See https://render.com/docs/blueprint-spec for more info on render blueprints
  - type: worker
    name: queue
    region: oregon
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery --app tasks worker --loglevel info --concurrency 4"
    autoDeploy: false
    envVars:
      - key: redis://red-cgr84kgrddl6f7enda00:6379
        fromService:
          name: cookpiredis
          type: redis
          property: connectionString
  - type: web
    name: cookpishare
    env: python
    plan: free
    # A requirements.txt file must exist
    buildCommand: pip install -r requirements.txt
    # A src/app.py file must exist and contain `server=app.server`
    startCommand: gunicorn --chdir src app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.7.4
      - key: redis://red-cgr84kgrddl6f7enda00:6379 # this must match the name of the environment variable used in production.rb
        fromService:
          type: redis
          name: cookpiredis
          property: connectionString
  - type: web
    name: flower
    region: oregon
    plan: free
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery flower --app tasks --loglevel info"
    autoDeploy: false
    envVars:
      - key: redis://red-cgr84kgrddl6f7enda00:6379
        fromService:
          type: redis
          name: cookpiredis
          property: connectionString
  - type: redis
    name: cookpiredis
    region: oregon
    plan: starter # we choose a plan with persistence to ensure tasks are not lost upon restart
    maxmemoryPolicy: allkeys-lru # recommended policy for queues
    ipAllowList: [] # only allow internal connections